allow-preset-passphrase
default-cache-ttl 3600
default-cache-ttl-ssh 3600
max-cache-ttl 57600
pinentry-program /usr/bin/pinentry
quiet
enable-ssh-support

###+++--- GPGConf ---+++###
debug-level basic
log-file socket:///home/robert/.gnupg/log-socket
###+++--- GPGConf ---+++### Wed 20 Sep 2023 07:16:50 PM CDT
# GPGConf edited this configuration file.
# It will disable options before this marked block, but it will
# never change anything below these lines.
